version: '3.8'

services:
  # Base de Datos (MySQL 8.4)
  if-mysql:
    image: mysql:8.4
    container_name: if-mysql
    restart: always
    environment:
      MYSQL_DATABASE: integrity_family
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - if_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - if-net

  # Servidor de Mensajería (RabbitMQ)
  if-rabbit:
    image: rabbitmq:3-management
    container_name: if-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - if-net

  # Administrador Visual de DB (Puerto 8082)
  if-phpmyadmin:
    image: phpmyadmin
    container_name: if-phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: if-mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - if-mysql
    networks:
      - if-net

  # Backend (Spring Boot)
  if-backend:
    build: ./backend
    container_name: if-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://if-mysql:3306/integrity_family?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=if-rabbit
    depends_on:
      if-mysql:
        condition: service_healthy
    networks:
      - if-net

  # Frontend (Angular)
  if-frontend:
    build: ./frontend
    container_name: if-frontend
    ports:
      - "4200:4200"
    depends_on:
      - if-backend
    networks:
      - if-net

volumes:
  if_mysql_data:

networks:
  if-net:
    driver: bridge