-- V69: Snapshot del schema completo de producción (2026-06-16)
-- Crea con IF NOT EXISTS todas las tablas que existían en producción
-- vía ddl-auto=update pero nunca registradas en Flyway.
-- Esta migración es idempotente: las tablas ya creadas por V1-V68 se omiten.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `adaptive_adjustments` (
  `id` binary(16) NOT NULL,
  `family_id` bigint NOT NULL,
  `rule_type` varchar(50) NOT NULL,
  `reason` text NOT NULL,
  `status` varchar(30) NOT NULL,
  `created_at` datetime NOT NULL,
  `approved_at` datetime DEFAULT NULL,
  `applied_at` datetime DEFAULT NULL,
  `approved_by` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_adaptive_adjustments_family` (`family_id`),
  KEY `idx_adaptive_adjustments_status` (`status`),
  KEY `idx_adaptive_adjustments_family_status` (`family_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `admin_alerts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `message` text,
  `severity` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_read` tinyint(1) DEFAULT '0',
  `viewed` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `ai_inferences` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `context_hash` varchar(100) DEFAULT NULL,
  `input_summary` text,
  `inference_result` text,
  `priority` varchar(50) DEFAULT NULL,
  `prompt_used` text,
  `model_version` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_inferences_family` (`family_id`),
  KEY `idx_ai_inferences_created_at` (`created_at`),
  KEY `idx_ai_inferences_family_created_at` (`family_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `audit_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `event_type` varchar(60) NOT NULL,
  `actor_email` varchar(180) DEFAULT NULL,
  `actor_user_id` bigint DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `metadata_json` text,
  `occurred_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_audit_type_time` (`event_type`,`occurred_at`),
  KEY `idx_audit_actor` (`actor_user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `beta_feedback` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint DEFAULT NULL,
  `reporter_id` bigint DEFAULT NULL,
  `score` int NOT NULL,
  `comment` text,
  `type` varchar(255) DEFAULT NULL,
  `milestone_at_moment` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_beta_feedback_family` (`family_id`),
  KEY `idx_beta_feedback_reporter` (`reporter_id`),
  KEY `idx_beta_feedback_created_at` (`created_at`),
  CONSTRAINT `FKgtqli4lg8o7cxhnf7v0diqy05` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`),
  CONSTRAINT `FKs4idxv855l5ea8qwxagoer03c` FOREIGN KEY (`reporter_id`) REFERENCES `family_members` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `chat_messages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `sender` varchar(100) DEFAULT NULL,
  `content` text,
  `timestamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_ai` tinyint(1) DEFAULT '0',
  `member_id` bigint DEFAULT NULL,
  `session_id` bigint DEFAULT NULL,
  `emotional_snapshot` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_chat_family` (`family_id`),
  KEY `fk_cm_member` (`member_id`),
  KEY `fk_cm_session` (`session_id`),
  KEY `idx_chat_messages_created_at` (`created_at`),
  CONSTRAINT `fk_chat_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cm_member` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cm_session` FOREIGN KEY (`session_id`) REFERENCES `conversation_sessions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `checklist_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `description` text NOT NULL,
  `completed` tinyint(1) DEFAULT '0',
  `completed_by` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` datetime DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `source` varchar(50) DEFAULT NULL,
  `dimension` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_check_family` (`family_id`),
  CONSTRAINT `fk_check_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `checklist_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `member_id` bigint DEFAULT NULL,
  `milestone_key` varchar(50) DEFAULT NULL,
  `event_type` varchar(20) NOT NULL,
  `status` varchar(20) NOT NULL,
  `comment` varchar(500) DEFAULT NULL,
  `evidence_url` varchar(255) DEFAULT NULL,
  `source` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_checklist_logs_family` (`family_id`),
  KEY `idx_checklist_logs_member` (`member_id`),
  KEY `idx_checklist_logs_created_at` (`created_at`),
  CONSTRAINT `FKa6y0o782dp5rqjx2a3qbnsmtm` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`),
  CONSTRAINT `FKc4y3kekhs7c6bsjjb3k1kspv8` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `conversation_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `member_id` bigint DEFAULT NULL,
  `goal` varchar(20) NOT NULL DEFAULT 'GENERAL' COMMENT 'GENERAL | SUPPORT | REFLECTION | PLANNING | GUARDIAN_SYNC',
  `emotional_state` varchar(20) DEFAULT NULL COMMENT 'CALM | ANXIOUS | FRUSTRATED | HOPEFUL | CONFUSED | ENGAGED',
  `turn_count` int NOT NULL DEFAULT '0',
  `outcome` varchar(30) DEFAULT NULL COMMENT 'COMPLETED | ABANDONED | ESCALATED',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ended_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_cs_member` (`member_id`),
  KEY `idx_cs_family_member` (`family_id`,`member_id`),
  KEY `idx_cs_family_started` (`family_id`,`started_at`),
  CONSTRAINT `fk_cs_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cs_member` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `critical_days` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `day_date` date NOT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `severity` varchar(30) DEFAULT NULL,
  `ai_containment_guide` text,
  `category` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` text,
  `main_emotion` varchar(255) DEFAULT NULL,
  `member_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_cd_family` (`family_id`),
  CONSTRAINT `fk_cd_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `documentary_production_evidences` (
  `production_id` bigint NOT NULL,
  `evidence_id` bigint NOT NULL,
  KEY `FK6ryi80ns4peumlmypmyxnbodv` (`evidence_id`),
  KEY `FKnede9v5fl7mk0kmekir6y4uug` (`production_id`),
  CONSTRAINT `FK6ryi80ns4peumlmypmyxnbodv` FOREIGN KEY (`evidence_id`) REFERENCES `task_evidences` (`id`),
  CONSTRAINT `FKnede9v5fl7mk0kmekir6y4uug` FOREIGN KEY (`production_id`) REFERENCES `documentary_productions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `documentary_productions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `export_url` varchar(255) DEFAULT NULL,
  `reference_id` bigint DEFAULT NULL,
  `scope` enum('MISSION','MONTH','PILLAR','ROUTE_36','SPRINT','TRIMESTER') NOT NULL,
  `script_data` text,
  `status` enum('APPROVED','ARCHIVED','CURATED','DRAFT','GENERATED','PUBLISHED','REVIEWED') NOT NULL,
  `title` varchar(255) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `family_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKqpm89lsfyxrx7ybplgwlyd1nl` (`family_id`),
  CONSTRAINT `FKqpm89lsfyxrx7ybplgwlyd1nl` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `emotional_rule_signals` (
  `rule_id` bigint NOT NULL,
  `signal_name` varchar(60) NOT NULL,
  KEY `idx_ers_rule` (`rule_id`),
  CONSTRAINT `fk_ers_rule` FOREIGN KEY (`rule_id`) REFERENCES `emotional_rules` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `emotional_rules` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `rule_key` varchar(60) NOT NULL,
  `version` int NOT NULL DEFAULT '1',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `milestone_scope` varchar(20) DEFAULT '*',
  `member_role` varchar(20) DEFAULT '*',
  `temporal_window_days` int NOT NULL DEFAULT '14',
  `projection_label` varchar(60) DEFAULT NULL,
  `confidence_base` double NOT NULL DEFAULT '0.7',
  `risk_output` varchar(20) DEFAULT NULL,
  `created_by` varchar(50) DEFAULT 'RISK_ALGO_V1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_er_key_version` (`rule_key`,`version`),
  UNIQUE KEY `idx_er_key_version` (`rule_key`,`version`),
  KEY `idx_er_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `emotional_stimuli` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `type` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `media_url` varchar(1000) NOT NULL,
  `category` varchar(100) NOT NULL,
  `target_role` varchar(50) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `evaluation_answers` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `evaluation_id` bigint NOT NULL,
  `question_key` varchar(255) NOT NULL,
  `score` int NOT NULL,
  `dimension` varchar(30) DEFAULT NULL,
  `answered_at` datetime DEFAULT NULL COMMENT 'Momento en que se guardó esta respuesta',
  `question_id` bigint DEFAULT NULL COMMENT 'FK a questions.id (resolución de question_key)',
  `boolean_answer` tinyint(1) DEFAULT NULL COMMENT 'Respuesta Sí/No (1=Sí, 0=No); NULL si no aplica',
  `diagnostic_dimension` varchar(50) DEFAULT NULL COMMENT 'Dimensión específica del diagnóstico adaptativo v2',
  `consciousness_level` varchar(30) DEFAULT NULL COMMENT 'Etiqueta del nivel de conciencia en primera persona',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ans_eval_question` (`evaluation_id`,`question_key`),
  KEY `fk_ans_question` (`question_id`),
  CONSTRAINT `fk_ans_eval` FOREIGN KEY (`evaluation_id`) REFERENCES `evaluations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ans_question` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `evaluation_dimension_scores` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `evaluation_id` bigint NOT NULL,
  `dimension_name` varchar(100) NOT NULL,
  `score` double NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_eds_eval` (`evaluation_id`),
  CONSTRAINT `fk_eds_eval` FOREIGN KEY (`evaluation_id`) REFERENCES `evaluations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `evaluations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `member_id` bigint DEFAULT NULL,
  `status` varchar(30) NOT NULL,
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finalized_at` datetime DEFAULT NULL,
  `has_crisis` tinyint(1) DEFAULT '0',
  `icf` double DEFAULT NULL,
  `milestone_key` varchar(50) DEFAULT NULL,
  `spiritual_synthesis` text,
  `algorithm_version` varchar(50) DEFAULT NULL,
  `critical_dimension` varchar(50) DEFAULT NULL,
  `risk_level` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_eval_family` (`family_id`),
  KEY `fk_eval_member` (`member_id`),
  CONSTRAINT `fk_eval_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`),
  CONSTRAINT `fk_eval_member` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `failed_login_attempts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `email` varchar(180) NOT NULL,
  `attempted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_address` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fla_email_time` (`email`,`attempted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `families` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text,
  `family_code` varchar(255) DEFAULT NULL,
  `current_milestone` varchar(255) DEFAULT NULL,
  `pin_hash` varchar(255) DEFAULT NULL,
  `whatsapp` varchar(255) DEFAULT NULL,
  `municipio` varchar(255) DEFAULT NULL,
  `country_code` varchar(255) DEFAULT NULL,
  `department_code` varchar(255) DEFAULT NULL,
  `created_by_id` bigint DEFAULT NULL,
  `sentinel_active` tinyint(1) DEFAULT '0',
  `icf_score` int DEFAULT NULL,
  `total_tasks` int DEFAULT NULL,
  `completed_tasks` int DEFAULT NULL,
  `last_report_sent_at` datetime DEFAULT NULL,
  `next_evaluation_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `milestone_started_at` datetime DEFAULT NULL,
  `milestone_icf_avg` double DEFAULT NULL,
  `guardian_member_id` bigint DEFAULT NULL,
  `guardian_since` datetime DEFAULT NULL,
  `rotation_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `participation_score` int NOT NULL DEFAULT '0',
  `pin` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `family_code` (`family_code`),
  UNIQUE KEY `uq_family_creator` (`created_by_id`),
  KEY `fk_families_guardian` (`guardian_member_id`),
  CONSTRAINT `fk_families_guardian` FOREIGN KEY (`guardian_member_id`) REFERENCES `family_members` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FKf1h8dgsifwll2ghd2a2hchab0` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_alerts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `alert_type` varchar(50) NOT NULL,
  `severity` varchar(20) NOT NULL,
  `title` varchar(100) NOT NULL,
  `detail` varchar(500) DEFAULT NULL,
  `inference_key` varchar(60) DEFAULT NULL,
  `evaluation_id` bigint DEFAULT NULL,
  `resolved` tinyint(1) NOT NULL DEFAULT '0',
  `resolved_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fa_family` (`family_id`),
  KEY `idx_fa_resolved` (`family_id`,`resolved`),
  KEY `idx_fa_severity` (`severity`),
  CONSTRAINT `fk_fa_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_behavioral_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `description` varchar(1000) NOT NULL,
  `severity` int NOT NULL,
  `occurred_at` timestamp NOT NULL,
  `repaired_at` timestamp NULL DEFAULT NULL,
  `repair_description` varchar(1000) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_behavioral_family_id` (`family_id`),
  CONSTRAINT `fk_behavioral_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_context_snapshots` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `connection_level` varchar(20) NOT NULL DEFAULT 'MEDIA',
  `stress_level` varchar(20) NOT NULL DEFAULT 'BAJO',
  `communication_trend` varchar(20) NOT NULL DEFAULT 'ESTABLE',
  `participation_level` varchar(20) NOT NULL DEFAULT 'MEDIA',
  `overall_trend` varchar(20) NOT NULL DEFAULT 'ESTABLE',
  `overall_mood` varchar(30) NOT NULL DEFAULT 'SERENO',
  `icf_current` double DEFAULT NULL,
  `risk_level` varchar(20) DEFAULT NULL,
  `days_without_activity` int NOT NULL DEFAULT '0',
  `current_streak` int NOT NULL DEFAULT '0',
  `active_rituals_count` int NOT NULL DEFAULT '0',
  `sprint_progress` double DEFAULT NULL,
  `alerts` json DEFAULT NULL,
  `recommendations` json DEFAULT NULL,
  `computed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `family_id` (`family_id`),
  CONSTRAINT `fk_ctx_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_dashboard_views` (
  `family_id` bigint NOT NULL,
  `adherence_percentage` double DEFAULT NULL,
  `family_code` varchar(255) DEFAULT NULL,
  `family_name` varchar(255) DEFAULT NULL,
  `latest_ai_recommendation` text,
  `latest_icf` decimal(38,2) DEFAULT NULL,
  `learning_entries_count` bigint DEFAULT NULL,
  `open_crises_count` bigint DEFAULT NULL,
  `risk_level` varchar(255) DEFAULT NULL,
  `tasks_completed` bigint DEFAULT NULL,
  `tasks_total` bigint DEFAULT NULL,
  `total_members` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`family_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_dna` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `valores` json DEFAULT NULL,
  `fortalezas` json DEFAULT NULL,
  `sombras` json DEFAULT NULL,
  `patrones` json DEFAULT NULL,
  `estilo_comunicacion` text,
  `ritmo_familiar` text,
  `potencial_oculto` json DEFAULT NULL,
  `narrativa_ia` text,
  `version` int NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `family_id` (`family_id`),
  CONSTRAINT `fk_dna_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_documentaries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `task_id` bigint DEFAULT NULL,
  `sprint_id` bigint DEFAULT NULL,
  `pillar_id` bigint DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `content` text,
  `source_type` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'COMPLETED',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_documentary_family` (`family_id`),
  KEY `fk_documentary_task` (`task_id`),
  KEY `fk_documentary_sprint` (`sprint_id`),
  CONSTRAINT `fk_documentary_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_documentary_sprint` FOREIGN KEY (`sprint_id`) REFERENCES `family_sprints` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_documentary_task` FOREIGN KEY (`task_id`) REFERENCES `plan_tasks` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_error_protocols` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `mission_failed` text,
  `feelings` text,
  `what_happened` text,
  `corrective_action` text,
  `who_helps` varchar(200) DEFAULT NULL,
  `agreement` text,
  `followup_date` date DEFAULT NULL,
  `learning` text,
  `closed` tinyint(1) NOT NULL DEFAULT '0',
  `current_step` varchar(20) NOT NULL DEFAULT 'DETECT',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `closed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_error_protocol_family` (`family_id`),
  CONSTRAINT `fk_error_protocol_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_gratitude_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `from_member` varchar(150) NOT NULL,
  `to_member` varchar(150) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_gratitude_family_id` (`family_id`),
  CONSTRAINT `fk_gratitude_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_identity_profile` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `communication_style` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'UNKNOWN' COMMENT 'RESERVED|EXPRESSIVE|CONFLICTIVE|AVOIDANT|COLLABORATIVE',
  `conflict_style` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'UNKNOWN' COMMENT 'CONFRONTATIONAL|AVOIDANT|NEGOTIATING|EXPLOSIVE|PASSIVE',
  `ritual_patterns` text COLLATE utf8mb4_unicode_ci COMMENT 'JSON array de rituales familiares',
  `stress_triggers` text COLLATE utf8mb4_unicode_ci COMMENT 'JSON array de factores de estrés',
  `emotional_expression` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW|MEDIUM|HIGH',
  `adaptability_index` double NOT NULL DEFAULT '0.5',
  `identity_narrative` text COLLATE utf8mb4_unicode_ci COMMENT 'Narrativa generada por la IA sobre la familia',
  `evolution_stage` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'INITIAL' COMMENT 'INITIAL|RECOGNITION|ADJUSTMENT|CONSOLIDATION|AUTONOMOUS',
  `completed_cycles` int NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_family_identity` (`family_id`),
  CONSTRAINT `fk_identity_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `family_legacies` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `history_lessons` text,
  `history_conserve` text,
  `history_avoid_errors` text,
  `history_to_leave` text,
  `history_recognition` text,
  `constitution_family_name` varchar(200) DEFAULT NULL,
  `constitution_year` int DEFAULT NULL,
  `founding_principle` text,
  `commitments` text,
  `never_do` text,
  `conflict_resolution` text,
  `family_mission` text,
  `family_vision` text,
  `family_tagline` varchar(300) DEFAULT NULL,
  `letter_from` varchar(200) DEFAULT NULL,
  `letter_to` varchar(200) DEFAULT NULL,
  `letter_open_in_year` int DEFAULT NULL,
  `letter_content` text,
  `letter_sealed` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_family_legacies_family` (`family_id`),
  CONSTRAINT `fk_legacy_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_lineages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `lineage_code` varchar(255) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `anchor_generation` int NOT NULL DEFAULT '0' COMMENT '0=Responsable, negativo=pasado, positivo=futuro',
  `max_past_gen` int NOT NULL DEFAULT '-2' COMMENT 'Generacion mas antigua registrada',
  `max_future_gen` int NOT NULL DEFAULT '2' COMMENT 'Generacion mas futura proyectada',
  `vision_statement` text COMMENT 'Vision del legado familiar',
  `founding_year` varchar(10) DEFAULT NULL COMMENT 'Año aprox. de la generacion mas antigua',
  PRIMARY KEY (`id`),
  UNIQUE KEY `lineage_code` (`lineage_code`),
  KEY `idx_lineage_family` (`family_id`),
  CONSTRAINT `fk_lineage_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_logbook_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `situation` varchar(1000) NOT NULL,
  `difficulty_detected` varchar(1000) NOT NULL,
  `emotion_identified` varchar(255) NOT NULL,
  `understanding` varchar(1000) NOT NULL,
  `correction_action` varchar(1000) NOT NULL,
  `family_agreement` varchar(1000) NOT NULL,
  `progress_evidence` varchar(1000) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'OPEN',
  `created_by` varchar(120) DEFAULT NULL,
  `resolved_by` varchar(120) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_logbook_family_id` (`family_id`),
  KEY `idx_logbook_status` (`status`),
  CONSTRAINT `fk_logbook_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_longitudinal_state` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `icf_current` double DEFAULT NULL,
  `icf_30d_ago` double DEFAULT NULL,
  `icf_90d_ago` double DEFAULT NULL,
  `current_risk_level` varchar(255) DEFAULT NULL,
  `risk_trend` varchar(255) DEFAULT NULL,
  `dim_emociones` double DEFAULT NULL,
  `dim_comunicacion` double DEFAULT NULL,
  `dim_habitos` double DEFAULT NULL,
  `dim_tiempos` double DEFAULT NULL,
  `critical_dimension` varchar(255) DEFAULT NULL,
  `crisis_count_30d` int DEFAULT '0',
  `crisis_count_total` int DEFAULT '0',
  `last_crisis_at` datetime(6) DEFAULT NULL,
  `consecutive_deteriorations` int DEFAULT '0',
  `consecutive_improvements` int DEFAULT '0',
  `communication_collapse_active` tinyint(1) DEFAULT '0',
  `evolution_phase` varchar(255) DEFAULT NULL,
  `narrative_stage` varchar(255) DEFAULT NULL,
  `consciousness_level` int DEFAULT NULL,
  `consciousness_label` varchar(255) DEFAULT NULL,
  `plan_adherence_percent` double DEFAULT NULL,
  `inactivity_days` int DEFAULT '0',
  `last_assessment_at` datetime(6) DEFAULT NULL,
  `last_journal_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `family_id` (`family_id`),
  UNIQUE KEY `UKei41n7ffq8lrhwef8qp6mx13k` (`family_id`),
  KEY `idx_longitudinal_risk_trend` (`risk_trend`),
  KEY `idx_longitudinal_crisis_count` (`crisis_count_30d`),
  KEY `idx_longitudinal_deterioration` (`consecutive_deteriorations`),
  KEY `idx_longitudinal_last_crisis` (`last_crisis_at`),
  CONSTRAINT `fk_longitudinal_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_members` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `user_id` bigint DEFAULT NULL,
  `full_name` varchar(255) NOT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `joined_at` datetime DEFAULT NULL,
  `age` int DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `autonomy_level` int DEFAULT '50',
  `responsibility_level` int DEFAULT '50',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `fk_mem_f` (`family_id`),
  KEY `fk_mem_u` (`user_id`),
  CONSTRAINT `fk_mem_f` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`),
  CONSTRAINT `fk_mem_u` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_memory` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `memory_type` enum('EPISODIC','IDENTITY','PROCEDURAL','SEMANTIC') COLLATE utf8mb4_unicode_ci NOT NULL,
  `semantic_key` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `importance_score` double NOT NULL DEFAULT '0.5',
  `source_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'EVALUATION|REFLECTION|LEARNING_ENTRY|AI_INFERENCE|MANUAL',
  `source_id` bigint DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL COMMENT 'NULL = no expira; se usa para compresión cognitiva',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_family_memory_family_type` (`family_id`,`memory_type`),
  KEY `idx_family_memory_importance` (`family_id`,`importance_score` DESC),
  KEY `idx_family_memory_semantic` (`family_id`,`semantic_key`),
  KEY `idx_family_memory_expires` (`expires_at`),
  CONSTRAINT `fk_family_memory_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `family_metrics_snapshots` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `adherence` double DEFAULT NULL,
  `communication_score` double DEFAULT NULL,
  `convivence_index` double DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `emotions_score` double DEFAULT NULL,
  `family_id` bigint NOT NULL,
  `participation` double DEFAULT NULL,
  `risk_level` varchar(50) DEFAULT NULL,
  `snapshot_date` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_missions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `category` varchar(100) NOT NULL DEFAULT 'CONEXION',
  `duration_minutes` int NOT NULL DEFAULT '60',
  `status` varchar(50) NOT NULL DEFAULT 'PENDING',
  `created_by_member_id` bigint DEFAULT NULL,
  `activated_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_fm_family` (`family_id`),
  KEY `fk_fm_creator` (`created_by_member_id`),
  CONSTRAINT `fk_fm_creator` FOREIGN KEY (`created_by_member_id`) REFERENCES `family_members` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fm_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_movies` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `period_label` varchar(100) NOT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `evidences_count` int NOT NULL DEFAULT '0',
  `gratitudes_count` int NOT NULL DEFAULT '0',
  `missions_completed` int NOT NULL DEFAULT '0',
  `crises_count` int NOT NULL DEFAULT '0',
  `rituals_completed` int NOT NULL DEFAULT '0',
  `days_active` int NOT NULL DEFAULT '0',
  `best_streak` int NOT NULL DEFAULT '0',
  `icf_start` double DEFAULT NULL,
  `icf_end` double DEFAULT NULL,
  `icf_delta` double DEFAULT NULL,
  `opening_line` text,
  `chapter_1` text,
  `chapter_2` text,
  `chapter_3` text,
  `mentor_letter` text,
  `highlight_quote` text,
  `generated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `generation_model` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_movie_family_period` (`family_id`,`period_start`),
  CONSTRAINT `fk_movie_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_predictions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `prediction_type` varchar(50) NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text,
  `confidence` int NOT NULL,
  `time_horizon` varchar(30) DEFAULT NULL,
  `recommended_action` text,
  `status` varchar(20) DEFAULT 'ACTIVE',
  `predicted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pred_family_status` (`family_id`,`status`),
  CONSTRAINT `fk_pred_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_rituals` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `ritual_type` varchar(40) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `title` varchar(200) NOT NULL,
  `description` text,
  `guided_steps` json DEFAULT NULL,
  `trigger_context` varchar(500) DEFAULT NULL,
  `triggered_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `activated_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `dismissed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ritual_family_status` (`family_id`,`status`),
  KEY `idx_ritual_type_date` (`family_id`,`ritual_type`,`triggered_at`),
  CONSTRAINT `fk_ritual_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_sprints` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `objective` varchar(255) NOT NULL,
  `risk_dimension` varchar(50) NOT NULL,
  `duration_days` int NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `status` varchar(30) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `mission_task_id` bigint DEFAULT NULL COMMENT 'ID del plan_task (misión del plan de transformación) que auto-generó este sprint. NULL si fue creado manualmente.',
  PRIMARY KEY (`id`),
  KEY `idx_sprint_family_status` (`family_id`,`status`),
  KEY `fk_sprint_mission_task` (`mission_task_id`),
  CONSTRAINT `fk_sprint_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sprint_mission_task` FOREIGN KEY (`mission_task_id`) REFERENCES `plan_tasks` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_tree_links` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `parent_family_id` bigint NOT NULL,
  `child_family_id` bigint NOT NULL,
  `relationship` varchar(80) NOT NULL DEFAULT 'descendant',
  `linked_by_member` varchar(150) DEFAULT NULL,
  `linked_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `note` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `child_family_id` (`child_family_id`),
  UNIQUE KEY `uq_tree_link` (`parent_family_id`,`child_family_id`),
  CONSTRAINT `fk_tree_child` FOREIGN KEY (`child_family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tree_parent` FOREIGN KEY (`parent_family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_twin_profiles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `behavioral_signature` text,
  `communication_pattern` varchar(60) DEFAULT NULL,
  `resilience_index` double DEFAULT NULL,
  `bonding_rhythm` varchar(60) DEFAULT NULL,
  `dominant_strength` varchar(100) DEFAULT NULL,
  `dominant_vulnerability` varchar(100) DEFAULT NULL,
  `detected_patterns` json DEFAULT NULL,
  `correlations` json DEFAULT NULL,
  `active_predictions` json DEFAULT NULL,
  `avg_days_between_crises` int DEFAULT NULL,
  `avg_recovery_days` int DEFAULT NULL,
  `peak_activity_day` varchar(20) DEFAULT NULL,
  `computed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_richness` varchar(20) DEFAULT 'LOW',
  PRIMARY KEY (`id`),
  UNIQUE KEY `family_id` (`family_id`),
  CONSTRAINT `fk_twin_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `family_values` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `icon` varchar(10) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `description` text,
  `sort_order` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_family_values_family` (`family_id`),
  CONSTRAINT `fk_value_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=120 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `feedbacks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `member_id` bigint DEFAULT NULL,
  `rating` int DEFAULT NULL,
  `comment` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_feed_family` (`family_id`),
  KEY `fk_feed_member` (`member_id`),
  CONSTRAINT `fk_feed_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`),
  CONSTRAINT `fk_feed_member` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `generational_messages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `from_family_id` bigint NOT NULL,
  `to_family_id` bigint DEFAULT NULL,
  `author_name` varchar(150) NOT NULL,
  `subject` varchar(200) DEFAULT NULL,
  `content` text NOT NULL,
  `message_type` varchar(40) NOT NULL DEFAULT 'LETTER',
  `sealed` tinyint(1) NOT NULL DEFAULT '1',
  `open_in_year` int DEFAULT NULL,
  `opened_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_gm_from` (`from_family_id`),
  CONSTRAINT `fk_gm_from` FOREIGN KEY (`from_family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `guardian_votes` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `voter_member_id` bigint NOT NULL,
  `nominated_member_id` bigint NOT NULL,
  `voted_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_one_vote_per_member` (`family_id`,`voter_member_id`),
  KEY `fk_gv_voter` (`voter_member_id`),
  KEY `fk_gv_nominated` (`nominated_member_id`),
  CONSTRAINT `fk_gv_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_gv_nominated` FOREIGN KEY (`nominated_member_id`) REFERENCES `family_members` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_gv_voter` FOREIGN KEY (`voter_member_id`) REFERENCES `family_members` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `inference_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `evaluation_id` bigint NOT NULL,
  `inference_key` varchar(50) DEFAULT NULL,
  `algo_version` int NOT NULL DEFAULT '1',
  `epistemic_state` varchar(20) NOT NULL DEFAULT 'INFERRED',
  `evidence_hash` varchar(64) NOT NULL,
  `icf_value` double DEFAULT NULL,
  `risk_level` varchar(20) DEFAULT NULL,
  `critical_dimension` varchar(50) DEFAULT NULL,
  `operational_state` varchar(20) DEFAULT NULL,
  `simulation_suspected` tinyint(1) DEFAULT NULL,
  `uncertainty_total` double DEFAULT NULL,
  `previous_version` bigint DEFAULT NULL,
  `revision_reason` varchar(200) DEFAULT NULL,
  `stabilized_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ir_evidence_hash` (`evidence_hash`),
  UNIQUE KEY `idx_ir_hash` (`evidence_hash`),
  KEY `idx_ir_family` (`family_id`),
  KEY `idx_ir_evaluation` (`evaluation_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `journal_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `compliance_status` varchar(50) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `emotion` varchar(100) DEFAULT NULL,
  `learning` text,
  `mood_after` int DEFAULT NULL,
  `observations` text,
  `origin` enum('CRISIS','PLAN','RISK','TASK') NOT NULL,
  `reflection` text,
  `risk_dimension` varchar(50) DEFAULT NULL,
  `status` enum('ACTIVE','ARCHIVED') NOT NULL,
  `title` varchar(200) NOT NULL,
  `family_id` bigint NOT NULL,
  `related_task_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK590fk67fqwjvwcwfbf46go2e4` (`family_id`),
  KEY `FK8ftwbnlskv91e4xqi48709kh3` (`related_task_id`),
  CONSTRAINT `FK590fk67fqwjvwcwfbf46go2e4` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`),
  CONSTRAINT `FK8ftwbnlskv91e4xqi48709kh3` FOREIGN KEY (`related_task_id`) REFERENCES `plan_tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `learned_skills` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `skill_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `conditions` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JSON array de condiciones activadoras',
  `recommended_strategy` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JSON array de acciones recomendadas',
  `dimension` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `success_rate` double NOT NULL DEFAULT '0',
  `reuse_count` int NOT NULL DEFAULT '0',
  `success_count` int NOT NULL DEFAULT '0',
  `created_by_ai` tinyint(1) NOT NULL DEFAULT '1',
  `confidence` double NOT NULL DEFAULT '0.5',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_applied_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_skill_name` (`skill_name`),
  KEY `idx_skill_success` (`success_rate` DESC),
  KEY `idx_skill_confidence` (`confidence` DESC),
  KEY `idx_learned_skills_name` (`skill_name`),
  KEY `idx_learned_skills_success` (`success_rate` DESC)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `learning_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `awareness_shift` text NOT NULL,
  `behavioral_change` text NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `family_id` bigint NOT NULL,
  `task_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK21k4s7xt0sfl43obba9dc1qox` (`family_id`),
  KEY `FK4o7ku993t60j8cux2rnnof8wx` (`task_id`),
  CONSTRAINT `FK21k4s7xt0sfl43obba9dc1qox` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`),
  CONSTRAINT `FK4o7ku993t60j8cux2rnnof8wx` FOREIGN KEY (`task_id`) REFERENCES `plan_tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lineage_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint NOT NULL,
  `event_year` varchar(20) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `event_type` varchar(50) DEFAULT 'milestone',
  `is_approximate` tinyint(1) DEFAULT '0',
  `sort_order` int DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_levent_member` (`member_id`),
  CONSTRAINT `fk_levent_member` FOREIGN KEY (`member_id`) REFERENCES `lineage_members` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lineage_generation_info` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `lineage_id` bigint NOT NULL,
  `generation_level` int NOT NULL COMMENT '-3=tatarabuelos ... 0=responsable ... +3=bisnietos',
  `generation_type` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'responsible',
  `title` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `summary` text COLLATE utf8mb4_unicode_ci,
  `context` text COLLATE utf8mb4_unicode_ci,
  `key_challenge` text COLLATE utf8mb4_unicode_ci,
  `key_achievement` text COLLATE utf8mb4_unicode_ci,
  `period_start` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `period_end` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lineage_gen` (`lineage_id`,`generation_level`),
  UNIQUE KEY `UK25uih3qge2lu1xym9dripswnj` (`lineage_id`,`generation_level`),
  KEY `idx_lgi_lineage` (`lineage_id`),
  CONSTRAINT `fk_lgi_lineage` FOREIGN KEY (`lineage_id`) REFERENCES `family_lineages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `lineage_members` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `lineage_id` bigint NOT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `avatar_initials` varchar(5) DEFAULT NULL,
  `avatar_color` varchar(255) DEFAULT NULL,
  `generation` int NOT NULL DEFAULT '0',
  `status` varchar(20) NOT NULL DEFAULT 'unknown',
  `birth_year` int DEFAULT NULL,
  `birth_year_approximate` tinyint(1) DEFAULT '0',
  `birth_date` date DEFAULT NULL,
  `death_year` int DEFAULT NULL,
  `death_date` date DEFAULT NULL,
  `origin` varchar(255) DEFAULT NULL,
  `role_label` varchar(255) DEFAULT NULL,
  `confidence_level` int DEFAULT '50',
  `data_source` varchar(255) DEFAULT NULL,
  `story` text,
  `position_x` float DEFAULT '0',
  `position_y` float DEFAULT '0',
  `family_member_id` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `generation_type` varchar(30) DEFAULT NULL COMMENT 'founding|builder|responsible|current|future|projected',
  `is_anchor` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 si es el nodo ancla del árbol',
  `valores` text COMMENT 'Valores que esta persona aportó o heredó',
  `aprendizajes` text COMMENT 'Aprendizajes clave de vida',
  `errores_superados` text COMMENT 'Errores o traumas superados',
  `tradiciones` text COMMENT 'Tradiciones que inició o preservó',
  `misiones_cumplidas` text COMMENT 'Logros y misiones familiares cumplidas',
  `legado_personal` text COMMENT 'Legado específico que dejó o dejará',
  `photo_url` varchar(500) DEFAULT NULL COMMENT 'URL de foto de perfil del miembro (opcional)',
  PRIMARY KEY (`id`),
  KEY `fk_lmember_fmember` (`family_member_id`),
  KEY `idx_lmember_lineage` (`lineage_id`),
  KEY `idx_lmember_gen` (`lineage_id`,`generation`),
  KEY `idx_lm_gen_type` (`generation_type`),
  KEY `idx_lm_anchor` (`is_anchor`),
  CONSTRAINT `fk_lmember_fmember` FOREIGN KEY (`family_member_id`) REFERENCES `family_members` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_lmember_lineage` FOREIGN KEY (`lineage_id`) REFERENCES `family_lineages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lineage_relationships` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `lineage_id` bigint NOT NULL,
  `from_member_id` bigint NOT NULL,
  `to_member_id` bigint NOT NULL,
  `relationship_type` varchar(50) DEFAULT 'biological',
  `is_couple` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_lrel_from` (`from_member_id`),
  KEY `fk_lrel_to` (`to_member_id`),
  KEY `idx_lrel_lineage` (`lineage_id`),
  CONSTRAINT `fk_lrel_from` FOREIGN KEY (`from_member_id`) REFERENCES `lineage_members` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_lrel_lineage` FOREIGN KEY (`lineage_id`) REFERENCES `family_lineages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_lrel_to` FOREIGN KEY (`to_member_id`) REFERENCES `lineage_members` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lts_attempts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `session_id` bigint NOT NULL,
  `version` int NOT NULL DEFAULT '1',
  `content` text NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_lts_att_session` (`session_id`),
  CONSTRAINT `fk_lts_att_session` FOREIGN KEY (`session_id`) REFERENCES `lts_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lts_comparisons` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `session_id` bigint NOT NULL,
  `v_old_id` bigint NOT NULL,
  `v_new_id` bigint NOT NULL,
  `diff_analysis` text NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_lts_comp_session` (`session_id`),
  KEY `fk_lts_comp_old` (`v_old_id`),
  KEY `fk_lts_comp_new` (`v_new_id`),
  CONSTRAINT `fk_lts_comp_new` FOREIGN KEY (`v_new_id`) REFERENCES `lts_attempts` (`id`),
  CONSTRAINT `fk_lts_comp_old` FOREIGN KEY (`v_old_id`) REFERENCES `lts_attempts` (`id`),
  CONSTRAINT `fk_lts_comp_session` FOREIGN KEY (`session_id`) REFERENCES `lts_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lts_corrections` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `hypothesis_id` bigint NOT NULL,
  `new_solution` text NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_lts_corr_hyp` (`hypothesis_id`),
  CONSTRAINT `fk_lts_corr_hyp` FOREIGN KEY (`hypothesis_id`) REFERENCES `lts_hypotheses` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lts_errors` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `attempt_id` bigint NOT NULL,
  `error_type` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_lts_err_attempt` (`attempt_id`),
  CONSTRAINT `fk_lts_err_attempt` FOREIGN KEY (`attempt_id`) REFERENCES `lts_attempts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lts_hypotheses` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `error_id` bigint NOT NULL,
  `content` text NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_lts_hyp_error` (`error_id`),
  CONSTRAINT `fk_lts_hyp_error` FOREIGN KEY (`error_id`) REFERENCES `lts_errors` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lts_insights` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `session_id` bigint NOT NULL,
  `what_learned` text NOT NULL,
  `transfer` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_lts_ins_session` (`session_id`),
  CONSTRAINT `fk_lts_ins_session` FOREIGN KEY (`session_id`) REFERENCES `lts_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `lts_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `member_id` bigint NOT NULL,
  `topic` varchar(255) NOT NULL,
  `objective` text NOT NULL,
  `status` varchar(30) DEFAULT 'ACTIVE',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_lts_family` (`family_id`),
  KEY `fk_lts_member` (`member_id`),
  CONSTRAINT `fk_lts_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_lts_member` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `member_identity_profiles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint NOT NULL,
  `communication_style` varchar(20) DEFAULT NULL COMMENT 'DIRECT | REFLECTIVE | AVOIDANT | ASSERTIVE',
  `reflexivity_level` int DEFAULT NULL,
  `emotional_sensitivity` int DEFAULT NULL,
  `evasion_patterns` text COMMENT 'JSON array — temas o dinámicas que el miembro evita',
  `motivators` text COMMENT 'JSON array — qué activa la participación del miembro',
  `change_resistance` varchar(10) NOT NULL DEFAULT 'MED' COMMENT 'LOW | MED | HIGH',
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `member_id` (`member_id`),
  KEY `idx_mip_member` (`member_id`),
  CONSTRAINT `fk_mip_member` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `member_relation_edges` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `member_a_id` bigint NOT NULL,
  `member_b_id` bigint NOT NULL,
  `relationship_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OTHER',
  `dynamic_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'BALANCED',
  `cohesion_score` double NOT NULL DEFAULT '50',
  `tension_score` double NOT NULL DEFAULT '30',
  `communication_score` double NOT NULL DEFAULT '50',
  `evolution_trend` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'STABLE',
  `role_a` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NEUTRAL',
  `role_b` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NEUTRAL',
  `from_evaluation_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_edge_pair` (`family_id`,`member_a_id`,`member_b_id`),
  KEY `idx_edge_family` (`family_id`),
  KEY `idx_edge_member_a` (`member_a_id`),
  KEY `idx_edge_member_b` (`member_b_id`),
  CONSTRAINT `fk_edge_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`),
  CONSTRAINT `fk_edge_member_a` FOREIGN KEY (`member_a_id`) REFERENCES `family_members` (`id`),
  CONSTRAINT `fk_edge_member_b` FOREIGN KEY (`member_b_id`) REFERENCES `family_members` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `milestone_definitions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(10) NOT NULL,
  `description` text,
  `duration_days` int DEFAULT NULL,
  `label` varchar(255) NOT NULL,
  `order_index` int DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK7kmvgajpob512oqlmmik2mefy` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `milestones` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `milestone_key` varchar(50) NOT NULL,
  `status` varchar(30) NOT NULL,
  `reached_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_ms_family` (`family_id`),
  CONSTRAINT `fk_ms_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `mission_adjustments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action` varchar(50) DEFAULT NULL,
  `new_difficulty` varchar(50) DEFAULT NULL,
  `new_due_date` varchar(50) DEFAULT NULL,
  `new_frequency` varchar(50) DEFAULT NULL,
  `old_difficulty` varchar(50) DEFAULT NULL,
  `old_due_date` varchar(50) DEFAULT NULL,
  `old_frequency` varchar(50) DEFAULT NULL,
  `reason` text,
  `plan_adjustment_id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKel0m4qdh6y6bbwu8tvb5f3s79` (`plan_adjustment_id`),
  KEY `FKmm6rtx0ak6fpq8ym0r3yavhq2` (`task_id`),
  CONSTRAINT `FKel0m4qdh6y6bbwu8tvb5f3s79` FOREIGN KEY (`plan_adjustment_id`) REFERENCES `plan_adjustments` (`id`),
  CONSTRAINT `FKmm6rtx0ak6fpq8ym0r3yavhq2` FOREIGN KEY (`task_id`) REFERENCES `plan_tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `mission_templates` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text,
  `category` varchar(100) NOT NULL DEFAULT 'CONEXION',
  `duration_minutes` int NOT NULL DEFAULT '60',
  `difficulty` varchar(50) NOT NULL DEFAULT 'FACIL',
  `emoji` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `narrative_chapters` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `chapter_number` int NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci,
  `phase` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `icf_at_open` double DEFAULT NULL,
  `icf_at_close` double DEFAULT NULL,
  `key_event` varchar(400) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `turning_point` tinyint(1) NOT NULL DEFAULT '0',
  `opened_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `closed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_narrative_family` (`family_id`),
  KEY `idx_narrative_open` (`family_id`,`closed_at`),
  CONSTRAINT `fk_narrative_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notification_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint DEFAULT NULL,
  `message` text,
  `phone_number` varchar(255) DEFAULT NULL,
  `recipient_name` varchar(255) DEFAULT NULL,
  `recipient_role` varchar(255) DEFAULT NULL,
  `sent_at` datetime(6) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `viewed` bit(1) NOT NULL,
  `member_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK5dluf4tuueiyy5c1n9nrauok1` (`family_id`),
  KEY `FKqbugn7d9deqb7sjyr9pyfe3ls` (`member_id`),
  CONSTRAINT `FK5dluf4tuueiyy5c1n9nrauok1` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`),
  CONSTRAINT `FKqbugn7d9deqb7sjyr9pyfe3ls` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `participation_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `member_id` bigint DEFAULT NULL,
  `event_type` varchar(30) NOT NULL COMMENT 'CHAT_MESSAGE | MISSION_COMPLETED | EVIDENCE_SUBMITTED | LOGBOOK_ENTRY',
  `occurred_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pe_family_occurred` (`family_id`,`occurred_at`),
  KEY `idx_pe_member_occurred` (`member_id`,`occurred_at`),
  CONSTRAINT `fk_pe_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pe_member` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `password_reset_tokens` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `token_hash` varchar(120) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token_hash` (`token_hash`),
  KEY `fk_prt_user` (`user_id`),
  CONSTRAINT `fk_prt_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `plan_adjustments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `adjustment_type` varchar(50) DEFAULT NULL,
  `approved_at` datetime(6) DEFAULT NULL,
  `approved_by` varchar(120) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `reason` text,
  `status` enum('APPLIED','APPROVED','PROPOSED','REJECTED','REVERTED') NOT NULL,
  `family_plan_id` bigint NOT NULL,
  `source_inference_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK6iofx8q0edd5srv6598awo0g0` (`family_plan_id`),
  KEY `FKsvwidun8d6fj1r8apdf6rkf32` (`source_inference_id`),
  CONSTRAINT `FK6iofx8q0edd5srv6598awo0g0` FOREIGN KEY (`family_plan_id`) REFERENCES `plans` (`id`),
  CONSTRAINT `FKsvwidun8d6fj1r8apdf6rkf32` FOREIGN KEY (`source_inference_id`) REFERENCES `ai_inferences` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `plan_task_steps` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `completed` bit(1) NOT NULL,
  `detail` text NOT NULL,
  `type` enum('EJECUTAR','EVALUAR','PLANIFICAR') NOT NULL,
  `logbook_entry_id` bigint DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKt6pnod47dysscf9c7oeejhfb8` (`logbook_entry_id`),
  KEY `FKbwg3ung7m9qmj86xpm00s2tqg` (`task_id`),
  CONSTRAINT `FKbwg3ung7m9qmj86xpm00s2tqg` FOREIGN KEY (`task_id`) REFERENCES `plan_tasks` (`id`),
  CONSTRAINT `FKcjq43e2c4d8fbtt1cn6hg1ycj` FOREIGN KEY (`logbook_entry_id`) REFERENCES `family_logbook_entries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `plan_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `completed` tinyint(1) DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` datetime DEFAULT NULL,
  `due_date` datetime DEFAULT NULL,
  `dimension` varchar(255) DEFAULT NULL,
  `periodicity_months` int DEFAULT NULL,
  `responsible_id` bigint DEFAULT NULL,
  `milestone_id` bigint DEFAULT NULL,
  `fase` varchar(255) DEFAULT NULL,
  `riesgo_asociado` varchar(255) DEFAULT NULL,
  `objetivo` text,
  `accion_concreta` text,
  `indicador_cumplimiento` text,
  `evidencia_requerida` text,
  `impacto_icf` int DEFAULT NULL,
  `pillar_name` varchar(50) DEFAULT NULL,
  `milestone_code` varchar(50) DEFAULT NULL,
  `member_type` varchar(50) DEFAULT NULL,
  `risk_type` varchar(100) DEFAULT NULL,
  `mission_generator` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_task_plan` (`plan_id`),
  KEY `fk_task_resp` (`responsible_id`),
  KEY `FK7mno5aa2sw5t4kfadg077t4vx` (`milestone_id`),
  CONSTRAINT `FK7mno5aa2sw5t4kfadg077t4vx` FOREIGN KEY (`milestone_id`) REFERENCES `milestone_definitions` (`id`),
  CONSTRAINT `fk_task_plan` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_task_resp` FOREIGN KEY (`responsible_id`) REFERENCES `family_members` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `plan_template_activities` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `duration_days` int DEFAULT NULL,
  `frequency` varchar(50) DEFAULT NULL,
  `phase` varchar(50) DEFAULT NULL,
  `template_code` varchar(50) NOT NULL,
  `title` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `plan_templates` (
  `code` varchar(50) NOT NULL,
  `dimension` varchar(50) NOT NULL,
  `name` varchar(150) NOT NULL,
  `risk_level` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `plans` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `evaluation_id` bigint DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ai_report` text,
  `ai_generated_at` datetime DEFAULT NULL,
  `vision_3y` text,
  PRIMARY KEY (`id`),
  KEY `fk_plan_family` (`family_id`),
  KEY `fk_plan_eval` (`evaluation_id`),
  CONSTRAINT `fk_plan_eval` FOREIGN KEY (`evaluation_id`) REFERENCES `evaluations` (`id`),
  CONSTRAINT `fk_plan_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `private_journal_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `title` varchar(200) NOT NULL,
  `content` text NOT NULL,
  `emotional_state` varchar(20) NOT NULL DEFAULT 'NEUTRAL',
  `category` varchar(30) NOT NULL DEFAULT 'REFLEXION',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_journal_user_created` (`user_id`,`created_at` DESC),
  CONSTRAINT `fk_journal_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `progress_snapshot_dimensions` (
  `snapshot_id` bigint NOT NULL,
  `delta_score` double DEFAULT NULL,
  `dimension_name` varchar(255) NOT NULL,
  PRIMARY KEY (`snapshot_id`,`dimension_name`),
  CONSTRAINT `FKc3ceh1o8ua42lyyuadu1viymw` FOREIGN KEY (`snapshot_id`) REFERENCES `progress_snapshots` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `progress_snapshots` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `current_evaluation_id` bigint NOT NULL,
  `previous_evaluation_id` bigint DEFAULT NULL,
  `milestone_code` varchar(50) DEFAULT NULL,
  `previous_icf` double DEFAULT NULL,
  `current_icf` double DEFAULT NULL,
  `delta_icf` double DEFAULT NULL,
  `classification` varchar(30) DEFAULT NULL,
  `interpretation` text,
  `recommended_action` text,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKbb78vdkpyty43jg4swxodeoi8` (`current_evaluation_id`),
  KEY `FKgdhjc6kvy9hl38iqy6vrygwx5` (`family_id`),
  KEY `FK6hhdgorjhyloi0wkuoabgcdsx` (`previous_evaluation_id`),
  CONSTRAINT `FK6hhdgorjhyloi0wkuoabgcdsx` FOREIGN KEY (`previous_evaluation_id`) REFERENCES `evaluations` (`id`),
  CONSTRAINT `FKbb78vdkpyty43jg4swxodeoi8` FOREIGN KEY (`current_evaluation_id`) REFERENCES `evaluations` (`id`),
  CONSTRAINT `FKgdhjc6kvy9hl38iqy6vrygwx5` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `questions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `question_key` varchar(255) DEFAULT NULL,
  `text` varchar(500) NOT NULL,
  `dimension` varchar(50) DEFAULT NULL,
  `area` varchar(50) DEFAULT NULL,
  `direction` varchar(20) DEFAULT 'POSITIVE',
  `version` varchar(20) DEFAULT '1.0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `vertice` int NOT NULL DEFAULT '0',
  `weight` int DEFAULT '1',
  `sort_order` int DEFAULT NULL,
  `pillar` varchar(50) DEFAULT NULL,
  `phase` varchar(50) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `severity_weight` double DEFAULT NULL,
  `detects_relapse` tinyint(1) NOT NULL DEFAULT '0',
  `requires_evidence` tinyint(1) NOT NULL DEFAULT '0',
  `reverse_question` tinyint(1) NOT NULL DEFAULT '0',
  `category` varchar(100) DEFAULT NULL,
  `adaptive_triggers` varchar(255) DEFAULT NULL,
  `evidence_type` varchar(50) DEFAULT NULL,
  `pillar_name` varchar(50) DEFAULT NULL,
  `milestone_code` varchar(50) DEFAULT NULL,
  `member_type` varchar(50) DEFAULT NULL,
  `risk_type` varchar(100) DEFAULT NULL,
  `mission_generator` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `question_key` (`question_key`)
) ENGINE=InnoDB AUTO_INCREMENT=1125 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `reflections` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `communication_improved` bit(1) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `difficulty` varchar(500) DEFAULT NULL,
  `emotional_impact` int DEFAULT NULL,
  `learning` varchar(1000) DEFAULT NULL,
  `repeat_intent` bit(1) DEFAULT NULL,
  `status` enum('COMPLETED','DRAFT') NOT NULL,
  `submitted_by` varchar(255) DEFAULT NULL,
  `family_id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKw8voy214qlhus983b7mp2b75` (`family_id`),
  KEY `FKq7cts3yixdea15f8u1lkt300k` (`task_id`),
  CONSTRAINT `FKq7cts3yixdea15f8u1lkt300k` FOREIGN KEY (`task_id`) REFERENCES `plan_tasks` (`id`),
  CONSTRAINT `FKw8voy214qlhus983b7mp2b75` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `reflective_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `member_id` bigint NOT NULL,
  `stimulus_id` bigint NOT NULL,
  `reflection` text NOT NULL,
  `emotional_score` int NOT NULL,
  `inference_result` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_refs_family` (`family_id`),
  KEY `fk_refs_member` (`member_id`),
  KEY `fk_refs_stimulus` (`stimulus_id`),
  CONSTRAINT `fk_refs_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_refs_member` FOREIGN KEY (`member_id`) REFERENCES `family_members` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_refs_stimulus` FOREIGN KEY (`stimulus_id`) REFERENCES `emotional_stimuli` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `refresh_tokens` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `expiry_date` datetime(6) NOT NULL,
  `revoked` bit(1) NOT NULL,
  `token` varchar(120) NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKghpmfn23vmxfu3spu3lfg4r2d` (`token`),
  KEY `FK1lih5y2npsf8u5o3vhdb9y0os` (`user_id`),
  CONSTRAINT `FK1lih5y2npsf8u5o3vhdb9y0os` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `risk_snapshots` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `risk_level` varchar(255) DEFAULT NULL,
  `score` double NOT NULL,
  `observation` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dimension_impact` varchar(255) DEFAULT NULL,
  `consciousness_label` varchar(255) DEFAULT NULL,
  `consciousness_level` int DEFAULT NULL,
  `has_crisis` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_risk_family` (`family_id`),
  CONSTRAINT `fk_risk_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `roles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `sentiment_reports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `executive_summary` text,
  `negative_percentage` double DEFAULT NULL,
  `neutral_percentage` double DEFAULT NULL,
  `positive_percentage` double DEFAULT NULL,
  `total_samples` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `sprint_dailies` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sprint_id` bigint NOT NULL,
  `member_name` varchar(120) NOT NULL,
  `checkin_date` date NOT NULL,
  `yesterday_text` text NOT NULL,
  `today_text` text NOT NULL,
  `blockages_text` text NOT NULL,
  `resolution_text` text NOT NULL,
  `emotional_indicator` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_daily_sprint_id` (`sprint_id`),
  CONSTRAINT `fk_daily_sprint` FOREIGN KEY (`sprint_id`) REFERENCES `family_sprints` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `sprint_missions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sprint_id` bigint NOT NULL,
  `description` varchar(500) NOT NULL,
  `status` varchar(30) NOT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mission_sprint_id` (`sprint_id`),
  CONSTRAINT `fk_mission_sprint` FOREIGN KEY (`sprint_id`) REFERENCES `family_sprints` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `sprint_retrospectives` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sprint_id` bigint NOT NULL,
  `what_went_well` text,
  `what_was_difficult` text,
  `what_learned` text,
  `what_to_adjust` text,
  `tension_level` int DEFAULT NULL,
  `mindful_compliance` int DEFAULT NULL,
  `shared_time` int DEFAULT NULL,
  `positive_interactions` int DEFAULT NULL,
  `emotional_persistence` int DEFAULT NULL,
  `consistency_score` int DEFAULT NULL,
  `ai_feedback` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_retro_sprint` (`sprint_id`),
  CONSTRAINT `fk_retro_sprint` FOREIGN KEY (`sprint_id`) REFERENCES `family_sprints` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `task_evidences` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint DEFAULT NULL,
  `family_id` bigint NOT NULL,
  `evidence_type` varchar(50) NOT NULL,
  `status` varchar(30) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `emotion` varchar(80) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `member_name` varchar(150) DEFAULT NULL,
  `media_data` longtext,
  `media_mime` varchar(80) DEFAULT NULL,
  `file_url` text,
  `text_content` longtext,
  `submitted_by` varchar(255) DEFAULT NULL,
  `ai_score` double DEFAULT NULL,
  `human_score` double DEFAULT NULL,
  `validated` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `validated_at` timestamp NULL DEFAULT NULL,
  `documentary_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_evidence_task_id` (`task_id`),
  KEY `idx_evidence_family_status` (`family_id`,`status`),
  KEY `fk_evidence_documentary` (`documentary_id`),
  CONSTRAINT `fk_evidence_documentary` FOREIGN KEY (`documentary_id`) REFERENCES `family_documentaries` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_evidence_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_evidence_task` FOREIGN KEY (`task_id`) REFERENCES `plan_tasks` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `transformation_states` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `onboarding_step` varchar(30) NOT NULL DEFAULT 'CREATE_FAMILY',
  `current_pillar` varchar(30) NOT NULL DEFAULT 'RECONOCIMIENTO',
  `current_month` int NOT NULL DEFAULT '1',
  `current_sprint_number` int NOT NULL DEFAULT '1',
  `active_mission_id` bigint DEFAULT NULL,
  `progress_percent` int NOT NULL DEFAULT '0',
  `milestone_label` varchar(10) NOT NULL DEFAULT 'M1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `family_id` (`family_id`),
  CONSTRAINT `fk_transformation_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `user_journals` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `category` varchar(50) DEFAULT NULL,
  `content` text NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `emotional_state` varchar(50) DEFAULT NULL,
  `title` varchar(200) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKrv23hjwqi77ufvmthlc55xxh4` (`user_id`),
  CONSTRAINT `FKrv23hjwqi77ufvmthlc55xxh4` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `user_roles` (
  `user_id` bigint NOT NULL,
  `role_id` bigint NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `fk_ur_role` (`role_id`),
  CONSTRAINT `fk_ur_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ur_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint DEFAULT NULL,
  `email` varchar(180) NOT NULL,
  `password_hash` varchar(120) NOT NULL,
  `full_name` varchar(150) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `account_locked_until` datetime DEFAULT NULL,
  `last_login_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `fk_users_family` (`family_id`),
  KEY `idx_users_email` (`email`),
  CONSTRAINT `fk_users_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `voice_audits` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `duration_seconds` int DEFAULT NULL,
  `family_id` bigint NOT NULL,
  `municipio` varchar(255) DEFAULT NULL,
  `processed_at` datetime(6) DEFAULT NULL,
  `provider_stt` varchar(255) DEFAULT NULL,
  `provider_tts` varchar(255) DEFAULT NULL,
  `success` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `weekly_plans` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `family_id` bigint NOT NULL,
  `sprint_number` int NOT NULL DEFAULT '1',
  `phase` varchar(20) NOT NULL,
  `daily_answers` json DEFAULT NULL,
  `week_start_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_weekly_plan` (`family_id`,`sprint_number`,`phase`),
  UNIQUE KEY `UK2ythe9anc9basqp1aaekrcynf` (`family_id`,`sprint_number`,`phase`),
  KEY `idx_weekly_plans_family` (`family_id`),
  CONSTRAINT `fk_weekly_plan_family` FOREIGN KEY (`family_id`) REFERENCES `families` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `weekly_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `weekly_plan_id` bigint NOT NULL,
  `description` text NOT NULL,
  `responsible` varchar(100) DEFAULT NULL,
  `when` varchar(100) DEFAULT NULL,
  `indicator` varchar(200) DEFAULT NULL,
  `done` tinyint(1) NOT NULL DEFAULT '0',
  `sort_order` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_weekly_task_plan` (`weekly_plan_id`),
  CONSTRAINT `fk_weekly_task_plan` FOREIGN KEY (`weekly_plan_id`) REFERENCES `weekly_plans` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
